server:
  port: 1234
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/token
    username: cadastra_eventos_app
    password: desafiotoken
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

